[phases.setup]
nixPkgs = ["nodejs_22"]
cmds = ["corepack enable"]

[phases.install]
cmds = ["corepack prepare pnpm@11.5.2 --activate", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"
