packages:
  - .

allowBuilds:
  esbuild: true
  lightningcss: true

overrides:
  srvx: ^0.11.16
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    tailwindcss: ">=4.0.0"
    vite: "*"
    vitest: "*"
