/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiTeamsRouteImport } from './routes/api.teams'
import { Route as ApiPlayersRouteImport } from './routes/api.players'
import { Route as ApiLeaderboardRouteImport } from './routes/api.leaderboard'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminScoresRouteImport } from './routes/admin.scores'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminImportsRouteImport } from './routes/admin.imports'
import { Route as TeamsTeamIdIndexRouteImport } from './routes/teams.$teamId.index'
import { Route as TeamsTeamIdEditRouteImport } from './routes/teams.$teamId.edit'
import { Route as ApiTeamsTeamIdRouteImport } from './routes/api.teams.$teamId'
import { Route as ApiPlayersPlayerIdRouteImport } from './routes/api.players.$playerId'
import { Route as ApiLeaderboardTeamIdRouteImport } from './routes/api.leaderboard.$teamId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiAdminTeamsRouteImport } from './routes/api.admin.teams'
import { Route as ApiAdminImportsRouteImport } from './routes/api.admin.imports'
import { Route as ApiAdminTeamsTeamIdRouteImport } from './routes/api.admin.teams.$teamId'
import { Route as ApiAdminScoresRecalculateRouteImport } from './routes/api.admin.scores.recalculate'
import { Route as ApiAdminScoresPlayersRouteImport } from './routes/api.admin.scores.players'
import { Route as ApiAdminImportsFifaSquadsRouteImport } from './routes/api.admin.imports.fifa-squads'
import { Route as ApiAdminImportsFifaGroupsRouteImport } from './routes/api.admin.imports.fifa-groups'
import { Route as ApiAdminImportsFbrefStatsRouteImport } from './routes/api.admin.imports.fbref-stats'
import { Route as ApiAdminImportsAllRouteImport } from './routes/api.admin.imports.all'
import { Route as ApiAdminImportsImportRunIdRouteImport } from './routes/api.admin.imports.$importRunId'
import { Route as ApiAdminScoresTeamsTeamIdRouteImport } from './routes/api.admin.scores.teams.$teamId'
import { Route as ApiAdminScoresPlayersPlayerIdRouteImport } from './routes/api.admin.scores.players.$playerId'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiTeamsRoute = ApiTeamsRouteImport.update({
  id: '/api/teams',
  path: '/api/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayersRoute = ApiPlayersRouteImport.update({
  id: '/api/players',
  path: '/api/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardRoute = ApiLeaderboardRouteImport.update({
  id: '/api/leaderboard',
  path: '/api/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScoresRoute = AdminScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportsRoute = AdminImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => AdminRoute,
} as any)
const TeamsTeamIdIndexRoute = TeamsTeamIdIndexRouteImport.update({
  id: '/teams/$teamId/',
  path: '/teams/$teamId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdEditRoute = TeamsTeamIdEditRouteImport.update({
  id: '/teams/$teamId/edit',
  path: '/teams/$teamId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamsTeamIdRoute = ApiTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => ApiTeamsRoute,
} as any)
const ApiPlayersPlayerIdRoute = ApiPlayersPlayerIdRouteImport.update({
  id: '/$playerId',
  path: '/$playerId',
  getParentRoute: () => ApiPlayersRoute,
} as any)
const ApiLeaderboardTeamIdRoute = ApiLeaderboardTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => ApiLeaderboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTeamsRoute = ApiAdminTeamsRouteImport.update({
  id: '/api/admin/teams',
  path: '/api/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminImportsRoute = ApiAdminImportsRouteImport.update({
  id: '/api/admin/imports',
  path: '/api/admin/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTeamsTeamIdRoute = ApiAdminTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => ApiAdminTeamsRoute,
} as any)
const ApiAdminScoresRecalculateRoute =
  ApiAdminScoresRecalculateRouteImport.update({
    id: '/api/admin/scores/recalculate',
    path: '/api/admin/scores/recalculate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminScoresPlayersRoute = ApiAdminScoresPlayersRouteImport.update({
  id: '/api/admin/scores/players',
  path: '/api/admin/scores/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminImportsFifaSquadsRoute =
  ApiAdminImportsFifaSquadsRouteImport.update({
    id: '/fifa-squads',
    path: '/fifa-squads',
    getParentRoute: () => ApiAdminImportsRoute,
  } as any)
const ApiAdminImportsFifaGroupsRoute =
  ApiAdminImportsFifaGroupsRouteImport.update({
    id: '/fifa-groups',
    path: '/fifa-groups',
    getParentRoute: () => ApiAdminImportsRoute,
  } as any)
const ApiAdminImportsFbrefStatsRoute =
  ApiAdminImportsFbrefStatsRouteImport.update({
    id: '/fbref-stats',
    path: '/fbref-stats',
    getParentRoute: () => ApiAdminImportsRoute,
  } as any)
const ApiAdminImportsAllRoute = ApiAdminImportsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => ApiAdminImportsRoute,
} as any)
const ApiAdminImportsImportRunIdRoute =
  ApiAdminImportsImportRunIdRouteImport.update({
    id: '/$importRunId',
    path: '/$importRunId',
    getParentRoute: () => ApiAdminImportsRoute,
  } as any)
const ApiAdminScoresTeamsTeamIdRoute =
  ApiAdminScoresTeamsTeamIdRouteImport.update({
    id: '/api/admin/scores/teams/$teamId',
    path: '/api/admin/scores/teams/$teamId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminScoresPlayersPlayerIdRoute =
  ApiAdminScoresPlayersPlayerIdRouteImport.update({
    id: '/$playerId',
    path: '/$playerId',
    getParentRoute: () => ApiAdminScoresPlayersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/admin/imports': typeof AdminImportsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/scores': typeof AdminScoresRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/leaderboard': typeof ApiLeaderboardRouteWithChildren
  '/api/players': typeof ApiPlayersRouteWithChildren
  '/api/teams': typeof ApiTeamsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/api/admin/imports': typeof ApiAdminImportsRouteWithChildren
  '/api/admin/teams': typeof ApiAdminTeamsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/leaderboard/$teamId': typeof ApiLeaderboardTeamIdRoute
  '/api/players/$playerId': typeof ApiPlayersPlayerIdRoute
  '/api/teams/$teamId': typeof ApiTeamsTeamIdRoute
  '/teams/$teamId/edit': typeof TeamsTeamIdEditRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/api/admin/imports/$importRunId': typeof ApiAdminImportsImportRunIdRoute
  '/api/admin/imports/all': typeof ApiAdminImportsAllRoute
  '/api/admin/imports/fbref-stats': typeof ApiAdminImportsFbrefStatsRoute
  '/api/admin/imports/fifa-groups': typeof ApiAdminImportsFifaGroupsRoute
  '/api/admin/imports/fifa-squads': typeof ApiAdminImportsFifaSquadsRoute
  '/api/admin/scores/players': typeof ApiAdminScoresPlayersRouteWithChildren
  '/api/admin/scores/recalculate': typeof ApiAdminScoresRecalculateRoute
  '/api/admin/teams/$teamId': typeof ApiAdminTeamsTeamIdRoute
  '/api/admin/scores/players/$playerId': typeof ApiAdminScoresPlayersPlayerIdRoute
  '/api/admin/scores/teams/$teamId': typeof ApiAdminScoresTeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/admin/imports': typeof AdminImportsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/scores': typeof AdminScoresRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/leaderboard': typeof ApiLeaderboardRouteWithChildren
  '/api/players': typeof ApiPlayersRouteWithChildren
  '/api/teams': typeof ApiTeamsRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/api/admin/imports': typeof ApiAdminImportsRouteWithChildren
  '/api/admin/teams': typeof ApiAdminTeamsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/leaderboard/$teamId': typeof ApiLeaderboardTeamIdRoute
  '/api/players/$playerId': typeof ApiPlayersPlayerIdRoute
  '/api/teams/$teamId': typeof ApiTeamsTeamIdRoute
  '/teams/$teamId/edit': typeof TeamsTeamIdEditRoute
  '/teams/$teamId': typeof TeamsTeamIdIndexRoute
  '/api/admin/imports/$importRunId': typeof ApiAdminImportsImportRunIdRoute
  '/api/admin/imports/all': typeof ApiAdminImportsAllRoute
  '/api/admin/imports/fbref-stats': typeof ApiAdminImportsFbrefStatsRoute
  '/api/admin/imports/fifa-groups': typeof ApiAdminImportsFifaGroupsRoute
  '/api/admin/imports/fifa-squads': typeof ApiAdminImportsFifaSquadsRoute
  '/api/admin/scores/players': typeof ApiAdminScoresPlayersRouteWithChildren
  '/api/admin/scores/recalculate': typeof ApiAdminScoresRecalculateRoute
  '/api/admin/teams/$teamId': typeof ApiAdminTeamsTeamIdRoute
  '/api/admin/scores/players/$playerId': typeof ApiAdminScoresPlayersPlayerIdRoute
  '/api/admin/scores/teams/$teamId': typeof ApiAdminScoresTeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/admin/imports': typeof AdminImportsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/scores': typeof AdminScoresRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/leaderboard': typeof ApiLeaderboardRouteWithChildren
  '/api/players': typeof ApiPlayersRouteWithChildren
  '/api/teams': typeof ApiTeamsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/api/admin/imports': typeof ApiAdminImportsRouteWithChildren
  '/api/admin/teams': typeof ApiAdminTeamsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/leaderboard/$teamId': typeof ApiLeaderboardTeamIdRoute
  '/api/players/$playerId': typeof ApiPlayersPlayerIdRoute
  '/api/teams/$teamId': typeof ApiTeamsTeamIdRoute
  '/teams/$teamId/edit': typeof TeamsTeamIdEditRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/api/admin/imports/$importRunId': typeof ApiAdminImportsImportRunIdRoute
  '/api/admin/imports/all': typeof ApiAdminImportsAllRoute
  '/api/admin/imports/fbref-stats': typeof ApiAdminImportsFbrefStatsRoute
  '/api/admin/imports/fifa-groups': typeof ApiAdminImportsFifaGroupsRoute
  '/api/admin/imports/fifa-squads': typeof ApiAdminImportsFifaSquadsRoute
  '/api/admin/scores/players': typeof ApiAdminScoresPlayersRouteWithChildren
  '/api/admin/scores/recalculate': typeof ApiAdminScoresRecalculateRoute
  '/api/admin/teams/$teamId': typeof ApiAdminTeamsTeamIdRoute
  '/api/admin/scores/players/$playerId': typeof ApiAdminScoresPlayersPlayerIdRoute
  '/api/admin/scores/teams/$teamId': typeof ApiAdminScoresTeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/leaderboard'
    | '/admin/imports'
    | '/admin/login'
    | '/admin/scores'
    | '/admin/teams'
    | '/api/health'
    | '/api/leaderboard'
    | '/api/players'
    | '/api/teams'
    | '/admin/'
    | '/api/admin/imports'
    | '/api/admin/teams'
    | '/api/auth/$'
    | '/api/leaderboard/$teamId'
    | '/api/players/$playerId'
    | '/api/teams/$teamId'
    | '/teams/$teamId/edit'
    | '/teams/$teamId/'
    | '/api/admin/imports/$importRunId'
    | '/api/admin/imports/all'
    | '/api/admin/imports/fbref-stats'
    | '/api/admin/imports/fifa-groups'
    | '/api/admin/imports/fifa-squads'
    | '/api/admin/scores/players'
    | '/api/admin/scores/recalculate'
    | '/api/admin/teams/$teamId'
    | '/api/admin/scores/players/$playerId'
    | '/api/admin/scores/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/leaderboard'
    | '/admin/imports'
    | '/admin/login'
    | '/admin/scores'
    | '/admin/teams'
    | '/api/health'
    | '/api/leaderboard'
    | '/api/players'
    | '/api/teams'
    | '/admin'
    | '/api/admin/imports'
    | '/api/admin/teams'
    | '/api/auth/$'
    | '/api/leaderboard/$teamId'
    | '/api/players/$playerId'
    | '/api/teams/$teamId'
    | '/teams/$teamId/edit'
    | '/teams/$teamId'
    | '/api/admin/imports/$importRunId'
    | '/api/admin/imports/all'
    | '/api/admin/imports/fbref-stats'
    | '/api/admin/imports/fifa-groups'
    | '/api/admin/imports/fifa-squads'
    | '/api/admin/scores/players'
    | '/api/admin/scores/recalculate'
    | '/api/admin/teams/$teamId'
    | '/api/admin/scores/players/$playerId'
    | '/api/admin/scores/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/leaderboard'
    | '/admin/imports'
    | '/admin/login'
    | '/admin/scores'
    | '/admin/teams'
    | '/api/health'
    | '/api/leaderboard'
    | '/api/players'
    | '/api/teams'
    | '/admin/'
    | '/api/admin/imports'
    | '/api/admin/teams'
    | '/api/auth/$'
    | '/api/leaderboard/$teamId'
    | '/api/players/$playerId'
    | '/api/teams/$teamId'
    | '/teams/$teamId/edit'
    | '/teams/$teamId/'
    | '/api/admin/imports/$importRunId'
    | '/api/admin/imports/all'
    | '/api/admin/imports/fbref-stats'
    | '/api/admin/imports/fifa-groups'
    | '/api/admin/imports/fifa-squads'
    | '/api/admin/scores/players'
    | '/api/admin/scores/recalculate'
    | '/api/admin/teams/$teamId'
    | '/api/admin/scores/players/$playerId'
    | '/api/admin/scores/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLeaderboardRoute: typeof ApiLeaderboardRouteWithChildren
  ApiPlayersRoute: typeof ApiPlayersRouteWithChildren
  ApiTeamsRoute: typeof ApiTeamsRouteWithChildren
  ApiAdminImportsRoute: typeof ApiAdminImportsRouteWithChildren
  ApiAdminTeamsRoute: typeof ApiAdminTeamsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  TeamsTeamIdEditRoute: typeof TeamsTeamIdEditRoute
  TeamsTeamIdIndexRoute: typeof TeamsTeamIdIndexRoute
  ApiAdminScoresPlayersRoute: typeof ApiAdminScoresPlayersRouteWithChildren
  ApiAdminScoresRecalculateRoute: typeof ApiAdminScoresRecalculateRoute
  ApiAdminScoresTeamsTeamIdRoute: typeof ApiAdminScoresTeamsTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/teams': {
      id: '/api/teams'
      path: '/api/teams'
      fullPath: '/api/teams'
      preLoaderRoute: typeof ApiTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/players': {
      id: '/api/players'
      path: '/api/players'
      fullPath: '/api/players'
      preLoaderRoute: typeof ApiPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard': {
      id: '/api/leaderboard'
      path: '/api/leaderboard'
      fullPath: '/api/leaderboard'
      preLoaderRoute: typeof ApiLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scores': {
      id: '/admin/scores'
      path: '/scores'
      fullPath: '/admin/scores'
      preLoaderRoute: typeof AdminScoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/imports': {
      id: '/admin/imports'
      path: '/imports'
      fullPath: '/admin/imports'
      preLoaderRoute: typeof AdminImportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teams/$teamId/': {
      id: '/teams/$teamId/'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof TeamsTeamIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/edit': {
      id: '/teams/$teamId/edit'
      path: '/teams/$teamId/edit'
      fullPath: '/teams/$teamId/edit'
      preLoaderRoute: typeof TeamsTeamIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teams/$teamId': {
      id: '/api/teams/$teamId'
      path: '/$teamId'
      fullPath: '/api/teams/$teamId'
      preLoaderRoute: typeof ApiTeamsTeamIdRouteImport
      parentRoute: typeof ApiTeamsRoute
    }
    '/api/players/$playerId': {
      id: '/api/players/$playerId'
      path: '/$playerId'
      fullPath: '/api/players/$playerId'
      preLoaderRoute: typeof ApiPlayersPlayerIdRouteImport
      parentRoute: typeof ApiPlayersRoute
    }
    '/api/leaderboard/$teamId': {
      id: '/api/leaderboard/$teamId'
      path: '/$teamId'
      fullPath: '/api/leaderboard/$teamId'
      preLoaderRoute: typeof ApiLeaderboardTeamIdRouteImport
      parentRoute: typeof ApiLeaderboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/teams': {
      id: '/api/admin/teams'
      path: '/api/admin/teams'
      fullPath: '/api/admin/teams'
      preLoaderRoute: typeof ApiAdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/imports': {
      id: '/api/admin/imports'
      path: '/api/admin/imports'
      fullPath: '/api/admin/imports'
      preLoaderRoute: typeof ApiAdminImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/teams/$teamId': {
      id: '/api/admin/teams/$teamId'
      path: '/$teamId'
      fullPath: '/api/admin/teams/$teamId'
      preLoaderRoute: typeof ApiAdminTeamsTeamIdRouteImport
      parentRoute: typeof ApiAdminTeamsRoute
    }
    '/api/admin/scores/recalculate': {
      id: '/api/admin/scores/recalculate'
      path: '/api/admin/scores/recalculate'
      fullPath: '/api/admin/scores/recalculate'
      preLoaderRoute: typeof ApiAdminScoresRecalculateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/scores/players': {
      id: '/api/admin/scores/players'
      path: '/api/admin/scores/players'
      fullPath: '/api/admin/scores/players'
      preLoaderRoute: typeof ApiAdminScoresPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/imports/fifa-squads': {
      id: '/api/admin/imports/fifa-squads'
      path: '/fifa-squads'
      fullPath: '/api/admin/imports/fifa-squads'
      preLoaderRoute: typeof ApiAdminImportsFifaSquadsRouteImport
      parentRoute: typeof ApiAdminImportsRoute
    }
    '/api/admin/imports/fifa-groups': {
      id: '/api/admin/imports/fifa-groups'
      path: '/fifa-groups'
      fullPath: '/api/admin/imports/fifa-groups'
      preLoaderRoute: typeof ApiAdminImportsFifaGroupsRouteImport
      parentRoute: typeof ApiAdminImportsRoute
    }
    '/api/admin/imports/fbref-stats': {
      id: '/api/admin/imports/fbref-stats'
      path: '/fbref-stats'
      fullPath: '/api/admin/imports/fbref-stats'
      preLoaderRoute: typeof ApiAdminImportsFbrefStatsRouteImport
      parentRoute: typeof ApiAdminImportsRoute
    }
    '/api/admin/imports/all': {
      id: '/api/admin/imports/all'
      path: '/all'
      fullPath: '/api/admin/imports/all'
      preLoaderRoute: typeof ApiAdminImportsAllRouteImport
      parentRoute: typeof ApiAdminImportsRoute
    }
    '/api/admin/imports/$importRunId': {
      id: '/api/admin/imports/$importRunId'
      path: '/$importRunId'
      fullPath: '/api/admin/imports/$importRunId'
      preLoaderRoute: typeof ApiAdminImportsImportRunIdRouteImport
      parentRoute: typeof ApiAdminImportsRoute
    }
    '/api/admin/scores/teams/$teamId': {
      id: '/api/admin/scores/teams/$teamId'
      path: '/api/admin/scores/teams/$teamId'
      fullPath: '/api/admin/scores/teams/$teamId'
      preLoaderRoute: typeof ApiAdminScoresTeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/scores/players/$playerId': {
      id: '/api/admin/scores/players/$playerId'
      path: '/$playerId'
      fullPath: '/api/admin/scores/players/$playerId'
      preLoaderRoute: typeof ApiAdminScoresPlayersPlayerIdRouteImport
      parentRoute: typeof ApiAdminScoresPlayersRoute
    }
  }
}

interface AdminRouteChildren {
  AdminImportsRoute: typeof AdminImportsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminScoresRoute: typeof AdminScoresRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminImportsRoute: AdminImportsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminScoresRoute: AdminScoresRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiLeaderboardRouteChildren {
  ApiLeaderboardTeamIdRoute: typeof ApiLeaderboardTeamIdRoute
}

const ApiLeaderboardRouteChildren: ApiLeaderboardRouteChildren = {
  ApiLeaderboardTeamIdRoute: ApiLeaderboardTeamIdRoute,
}

const ApiLeaderboardRouteWithChildren = ApiLeaderboardRoute._addFileChildren(
  ApiLeaderboardRouteChildren,
)

interface ApiPlayersRouteChildren {
  ApiPlayersPlayerIdRoute: typeof ApiPlayersPlayerIdRoute
}

const ApiPlayersRouteChildren: ApiPlayersRouteChildren = {
  ApiPlayersPlayerIdRoute: ApiPlayersPlayerIdRoute,
}

const ApiPlayersRouteWithChildren = ApiPlayersRoute._addFileChildren(
  ApiPlayersRouteChildren,
)

interface ApiTeamsRouteChildren {
  ApiTeamsTeamIdRoute: typeof ApiTeamsTeamIdRoute
}

const ApiTeamsRouteChildren: ApiTeamsRouteChildren = {
  ApiTeamsTeamIdRoute: ApiTeamsTeamIdRoute,
}

const ApiTeamsRouteWithChildren = ApiTeamsRoute._addFileChildren(
  ApiTeamsRouteChildren,
)

interface ApiAdminImportsRouteChildren {
  ApiAdminImportsImportRunIdRoute: typeof ApiAdminImportsImportRunIdRoute
  ApiAdminImportsAllRoute: typeof ApiAdminImportsAllRoute
  ApiAdminImportsFbrefStatsRoute: typeof ApiAdminImportsFbrefStatsRoute
  ApiAdminImportsFifaGroupsRoute: typeof ApiAdminImportsFifaGroupsRoute
  ApiAdminImportsFifaSquadsRoute: typeof ApiAdminImportsFifaSquadsRoute
}

const ApiAdminImportsRouteChildren: ApiAdminImportsRouteChildren = {
  ApiAdminImportsImportRunIdRoute: ApiAdminImportsImportRunIdRoute,
  ApiAdminImportsAllRoute: ApiAdminImportsAllRoute,
  ApiAdminImportsFbrefStatsRoute: ApiAdminImportsFbrefStatsRoute,
  ApiAdminImportsFifaGroupsRoute: ApiAdminImportsFifaGroupsRoute,
  ApiAdminImportsFifaSquadsRoute: ApiAdminImportsFifaSquadsRoute,
}

const ApiAdminImportsRouteWithChildren = ApiAdminImportsRoute._addFileChildren(
  ApiAdminImportsRouteChildren,
)

interface ApiAdminTeamsRouteChildren {
  ApiAdminTeamsTeamIdRoute: typeof ApiAdminTeamsTeamIdRoute
}

const ApiAdminTeamsRouteChildren: ApiAdminTeamsRouteChildren = {
  ApiAdminTeamsTeamIdRoute: ApiAdminTeamsTeamIdRoute,
}

const ApiAdminTeamsRouteWithChildren = ApiAdminTeamsRoute._addFileChildren(
  ApiAdminTeamsRouteChildren,
)

interface ApiAdminScoresPlayersRouteChildren {
  ApiAdminScoresPlayersPlayerIdRoute: typeof ApiAdminScoresPlayersPlayerIdRoute
}

const ApiAdminScoresPlayersRouteChildren: ApiAdminScoresPlayersRouteChildren = {
  ApiAdminScoresPlayersPlayerIdRoute: ApiAdminScoresPlayersPlayerIdRoute,
}

const ApiAdminScoresPlayersRouteWithChildren =
  ApiAdminScoresPlayersRoute._addFileChildren(
    ApiAdminScoresPlayersRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLeaderboardRoute: ApiLeaderboardRouteWithChildren,
  ApiPlayersRoute: ApiPlayersRouteWithChildren,
  ApiTeamsRoute: ApiTeamsRouteWithChildren,
  ApiAdminImportsRoute: ApiAdminImportsRouteWithChildren,
  ApiAdminTeamsRoute: ApiAdminTeamsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  TeamsTeamIdEditRoute: TeamsTeamIdEditRoute,
  TeamsTeamIdIndexRoute: TeamsTeamIdIndexRoute,
  ApiAdminScoresPlayersRoute: ApiAdminScoresPlayersRouteWithChildren,
  ApiAdminScoresRecalculateRoute: ApiAdminScoresRecalculateRoute,
  ApiAdminScoresTeamsTeamIdRoute: ApiAdminScoresTeamsTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
